version: '3.8'

services:
  latex:
    image: paperist/alpine-texlive-ja
    volumes:
      - .:/workdir
    working_dir: /workdir
    command: 
      - /bin/bash
      - -c
      - |
        platex tech-jsample.tex
        dvipdfmx tech-jsample.dvi